# Generated by Django 4.2.2 on 2025-04-22 00:40

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='job_images/')),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_unit', models.CharField(choices=[('hour', 'Per Hour'), ('week', 'Per Week'), ('month', 'Per Month')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="Add keywords like 'remote', 'part-time', etc.", size=None)),
                ('description', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
                ('marked_unavailable_by', models.ManyToManyField(blank=True, related_name='unavailable_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
