# Generated by Django 4.2.2 on 2025-04-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='apply_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='level',
            field=models.CharField(blank=True, choices=[('Entry', 'Entry'), ('Mid', 'Mid'), ('Senior', 'Senior')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='responsibilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='type',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_unit',
            field=models.CharField(blank=True, choices=[('hour', 'Per Hour'), ('week', 'Per Week'), ('month', 'Per Month')], max_length=10, null=True),
        ),
    ]
