# Generated by Django 4.2.2 on 2025-04-26 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobpost_company_name_jobpost_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='responsibilities',
        ),
    ]
